---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: llm-artifacts
spec:
  storageClassName: local-path
  capacity:
    storage: 10Gi
  accessModes:
    - ReadOnlyMany
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: llm-artifacts
    namespace: default
  hostPath:
    path: "/home/debian/huang06/ml-assignment/artifacts"
    type: Directory
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: llm-artifacts
  namespace: default
spec:
  storageClassName: local-path
  volumeName: llm-artifacts
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 10Gi
